# Aliases
alias nd='nix develop -c $SHELL'

case "$OSTYPE" in
  darwin*)
    alias nixos-rebuild="sudo darwin-rebuild switch --flake ~/.config/nix/#cyrus"
    ;;
  linux-gnu*)
    if command -v nixos-version >/dev/null 2>&1; then
      alias nixos-rebuild="sudo nixos-rebuild switch --flake '~/.config/nix/#nixos'"
    else
      alias nixos-rebuild="home-manager switch --flake ~/.config/nix/#cyrus"
    fi
    ;;
  *)
    alias nixos-rebuild="echo 'Unknown OS'"
    ;;
esac
alias turingnix-rebuild="home-manager switch --flake ~/.config/nix/\#cyrus@turingdb"

alias vi="nvim"

blame() {
  git log -n 5 --format='format:%h (%an: %ar) %s' --no-patch -L"$2",+1:"$1"
}

gca() {
  git commit -a -m "$1" && git commit --amend
}

gs() {
  git status --short
}

gu() {
  git fetch origin && git rebase origin/main
}

gane() {
  git commit --amend --no-edit
}

alias gst='git status'
alias gc="git commit && git commit --amend"
alias gsw="git switch"
alias glo="git log --oneline"
alias gd="git diff"
alias gdo="gd --name-status main"
alias gcp="git cherry-pick"
alias grv="git rev-parse --short HEAD"

# eval "$(direnv hook zsh)"

# Environment variables

# Personal Zsh configuration file. It is strongly recommended to keep all
# shell customization and configuration (including exported environment
# variables such as PATH) in this file or in files sourced from it.
#
# Documentation: https://github.com/romkatv/zsh4humans/blob/v5/README.md.

# Periodic auto-update on Zsh startup: 'ask' or 'no'.
# You can manually run `z4h update` to update everything.
zstyle ':z4h:' auto-update      'no'
# Ask whether to auto-update this often; has no effect if auto-update is 'no'.
zstyle ':z4h:' auto-update-days '28'

# Keyboard type: 'mac' or 'pc'.
zstyle ':z4h:bindkey' keyboard  'mac'

# Start tmux if not already in tmux.
# zstyle ':z4h:' start-tmux command tmux -u new -A -D -t z4h
zstyle ':z4h:' start-tmux no

# Whether to move prompt to the bottom when zsh starts and on Ctrl+L.
zstyle ':z4h:' prompt-at-bottom 'no'

# Mark up shell's output with semantic information.
zstyle ':z4h:' term-shell-integration 'yes'

# Right-arrow key accepts one character ('partial-accept') from
# command autosuggestions or the whole thing ('accept')?
zstyle ':z4h:autosuggestions' forward-char 'accept'

# Recursively traverse directories when TAB-completing files.
zstyle ':z4h:fzf-complete' recurse-dirs 'no'

# Enable direnv to automatically source .envrc files.
zstyle ':z4h:direnv'         enable 'no'
# Show "loading" and "unloading" notifications from direnv.
zstyle ':z4h:direnv:success' notify 'yes'

# Enable ('yes') or disable ('no') automatic teleportation of z4h over
# SSH when connecting to these hosts.
zstyle ':z4h:ssh:example-hostname1'   enable 'yes'
zstyle ':z4h:ssh:*.example-hostname2' enable 'no'
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*'                   enable 'no'

# Send these files over to the remote host when connecting over SSH to the
# enabled hosts.
zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh'

# Clone additional Git repositories from GitHub.
#
# This doesn't do anything apart from cloning the repository and keeping it
# up-to-date. Cloned files can be used after `z4h init`. This is just an
# example. If you don't plan to use Oh My Zsh, delete this line.
z4h install ohmyzsh/ohmyzsh || return

# Install or update core components (fzf, zsh-autosuggestions, etc.) and
# initialize Zsh. After this point console I/O is unavailable until Zsh
# is fully initialized. Everything that requires user interaction or can
# perform network I/O must be done above. Everything else is best done below.
z4h init || return

# Extend PATH.
path=(~/bin $path)

# Add clang-tools to path
path=($path /nix/store/4sz41xx038wkxqp2jkpkv5d58cddyizx-clang-tools-19.1.6/bin)
path=($path $HOME/.nix-profile/bin)

# Export environment variables.
export GPG_TTY=$TTY
export EDITOR=hx
export MANWIDTH=80

# Source additional local files if they exist.
z4h source ~/.env.zsh

# Use additional Git repositories pulled in with `z4h install`.
#
# This is just an example that you should delete. It does nothing useful.
z4h source ohmyzsh/ohmyzsh/lib/diagnostics.zsh  # source an individual file
z4h load   ohmyzsh/ohmyzsh/plugins/emoji-clock  # load a plugin

# Define key bindings.
z4h bindkey undo Ctrl+/   Shift+Tab  # undo the last command line change
z4h bindkey redo Option+/            # redo the last undone command line change

z4h bindkey z4h-cd-back    Shift+Left   # cd into the previous directory
z4h bindkey z4h-cd-forward Shift+Right  # cd into the next directory
z4h bindkey z4h-cd-up      Shift+Up     # cd into the parent directory
z4h bindkey z4h-cd-down    Shift+Down   # cd into a child directory

# Autoload functions.
autoload -Uz zmv

# Define functions and completions.
function md() { [[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1" }
compdef _directories md

# Define named directories: ~w <=> Windows home directory on WSL.
[[ -z $z4h_win_home ]] || hash -d w=$z4h_win_home

# Define aliases.
alias tree='tree -a -I .git'

# Add flags to existing aliases.
alias ls="${aliases[ls]:-ls} -A"

if [ -n "$TURING_HOME" ]; then
  echo '
  ████████╗██╗░░░██╗██████╗░██╗███╗░░██╗░██████╗░
  ╚══██╔══╝██║░░░██║██╔══██╗██║████╗░██║██╔════╝░
  ░░░██║░░░██║░░░██║██████╔╝██║██╔██╗██║██║░░██╗░
  ░░░██║░░░██║░░░██║██╔══██╗██║██║╚████║██║░░╚██╗
  ░░░██║░░░╚██████╔╝██║░░██║██║██║░╚███║╚██████╔╝
  ░░░╚═╝░░░░╚═════╝░╚═╝░░╚═╝╚═╝╚═╝░░╚══╝░╚═════╝░

  ██████╗░██╗░█████╗░░██████╗██╗░░░██╗░██████╗████████╗███████╗███╗░░░███╗░██████╗
  ██╔══██╗██║██╔══██╗██╔════╝╚██╗░██╔╝██╔════╝╚══██╔══╝██╔════╝████╗░████║██╔════╝
  ██████╦╝██║██║░░██║╚█████╗░░╚████╔╝░╚█████╗░░░░██║░░░█████╗░░██╔████╔██║╚█████╗░
  ██╔══██╗██║██║░░██║░╚═══██╗░░╚██╔╝░░░╚═══██╗░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗
  ██████╦╝██║╚█████╔╝██████╔╝░░░██║░░░██████╔╝░░░██║░░░███████╗██║░╚═╝░██║██████╔╝
  ╚═════╝░╚═╝░╚════╝░╚═════╝░░░░╚═╝░░░╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░

  '
  alias shell="uvx --from turingdb turingsh --host http://localhost:6666"
  # source /turing/setup.sh
  alias turingdb="/home/cyrus/turingdb/build/turing_install/bin/turingdb"
  source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

  nt() {
    /home/cyrus/new-test.sh "$1"
  }

fi

# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots     # no special treatment for file names with a leading dot
setopt no_auto_menu  # require an extra TAB press to open the completion menu
setopt auto_pushd    # cd && pushd
setopt always_to_end
